cq checks to make sure cromwell server is running before continuing

diff --git a/src/cq b/src/cq
--- a/src/cq
+++ b/src/cq
@@ -18,7 +18,7 @@ Options:
 -v: Indicate progress in stderr
 -1: Stop after one
 -k CASES_FN: file with list of all cases, one per line, used when RID1 not defined. Default: dat/cases.dat
--q QUERY: type of query, one of 'status', 'logs', 'workflowRoot', 'timing', 'duration', 'output', 'outputs', 'runlog', 'url'.  Default is `status`
+-q QUERY: type of query, one of 'check_server', 'status', 'logs', 'workflowRoot', 'timing', 'duration', 'outputs', 'runlog', 'url'.  Default is `status`
 -s STEP: define step of interest for use with 'logs' query
 -V: output query result only only (i.e., don't write case and workflow ID)
 -U: skip cases were WorkflowID is Unknown or Unassigned
@@ -39,6 +39,7 @@ If RID is - then read RID from STDIN.  If RID is not defined, read from CASES_FN
 Evaluates the following information for each case
 * The workflow ID of the cromwell job
 * Various queries from https://genome-cromwell.gsc.wustl.edu/  Supported queries:
+    * check_server - indicates whether server is running and accessible
     * status - Status of run
     * wid - Workflow ID
     * logs - List of stderr/stdout for each run.  All steps shown unless -s STEP is defined
@@ -62,10 +63,11 @@ CWL_OUTPUT is used to find the principal output of workflow, i.e., what is repor
   e.g., tindaisy.cwl.output_vcf
 
 Note that this script requires `jq` to be installed: https://stedolan.github.io/jq/download/
+Also check to make sure cromwell server is running
 EOF
 
 source src/cromwell_utils.sh
-SCRIPT=$(basename $0)
+SCRIPT=$(basename $0)   # used to identify this executable in error messages
 
 # read default from environment variable if possible, otherwise use default
 if [ -z $CROMWELL_URL ]; then
@@ -148,10 +150,6 @@ done
 
 shift $((OPTIND-1))
 
-# Confirm that `jq` is available
-# from https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
-command -v jq >/dev/null 2>&1 || { echo >&2 "ERROR: jq is not installed.  Quitting"; exit 1; }
-
 # If no DB, status is Unknown
 function get_status {
     WID=$1
@@ -224,44 +222,6 @@ function get_workflowRoot {
     echo "$S"
 }
 
-# This will return principal of workflow as specified by CWL_OUTPUT
-# TODO: we want to simplify this so user can get the principal output regardless of the CWL used, and without
-# having to pass parameter -W CWL_OUTPUT.  Issues:
-#  * some pipelines have more than one output
-#  * Output name of pipelines is not consistent.  For instance, may be .output or .output_vcf
-#    (though it would be good to standardize this)
-# Not doing full implementation now, but something like this works to select the .location of all outputs:
-#   echo "$R" | jq -r ".outputs[] |  .location" from https://stackoverflow.com/questions/45523425/getting-all-the-values-of-an-array-with-jq
-# If we standardize output name, then could do a search for it like above
-
-# We are removing get_output because workflows can have any number of outputs; use get_outputs instead
-#function get_output {
-#    WID=$1
-#    CWLO=$2
-#
-#    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/api/workflows/v1/$WID/outputs\" -H \"accept: application/json\" "
-#    if [ "$DEBUG" ]; then
-#        >&2 echo DEBUG: get_output Q = $Q
-#    fi
-#    R=$( eval $Q )
-#    test_exit_status $SCRIPT
-#    if [ "$DEBUG" ]; then
-#        >&2 echo DEBUG: get_output R = $R
-#    fi
-#
-#    JQQ=".outputs.\"$CWLO\".location" 
-#    if [ "$DEBUG" ]; then
-#        >&2 echo DEBUG: get_output JQQ = $JQQ
-#    fi
-#    S=$( echo "$R" | jq -r $JQQ )
-#    test_exit_status $SCRIPT
-#
-#    if [ "$DEBUG" ]; then
-#        >&2 echo DEBUG: get_output S = $S
-#    fi
-#    echo "$S"
-#}
-
 # This will return ALL outputs specified in CWL.  Note that this will consist of multiple lines
 function get_outputs {
     WID=$1
@@ -308,6 +268,31 @@ function get_runlog {
     printf "$STATUS\t$START\t$END"
 }
 
+# note that this does not require Run ID to be known
+function check_server {
+
+#    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/api/workflows/v1/$WID/outputs\" -H \"accept: application/json\" "
+
+    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/engine/v1/version\" -H \"accept: application/json\"  "
+    if [ "$DEBUG" ]; then
+        >&2 echo DEBUG: check_server Q = $Q
+    fi
+
+# If server is running
+    R=$( eval $Q )
+    RC=$?
+#    test_exit_status $SCRIPT
+    if [ "$DEBUG" ]; then
+        >&2 echo DEBUG: check_server status \$R = $R , return code = $RC 
+    fi
+
+    if [ $RC == 0 ]; then
+        printf "OK"
+    else
+        printf "ERROR"
+    fi
+}
+
 # duration returns the fields,
 # status, run_duration_minutes
 function get_duration {
@@ -327,6 +312,26 @@ function get_duration {
 
     printf "$STATUS\t$DIFF"
 }
+
+# Preliminary testing to make sure we can run:
+# * make sure `jq` is available
+# * test to make sure server running (unless query is check_server, which returns success)
+# Confirm that `jq` is available
+# from https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
+# This may happen if running outside of CromwellRunner container
+command -v jq >/dev/null 2>&1 || { echo >&2 "ERROR: jq is not installed.  Quitting"; exit 1; }
+
+# checking if server is running does not require information about cases or workflow IDs, so can be done immediately
+STATUS=$(check_server)
+if [ "$QUERY" == 'check_server' ]; then
+    STATUS=$(check_server)
+    >&2 echo $STATUS
+    exit 0
+elif [ "$STATUS" != "OK" ]; then
+    >&2 echo ERROR: Cromwell server does not seem to be running
+    exit 1
+fi
+
 
 # this allows us to get Run IDs in one of three ways:
 # 1: cq RID1 RID2 ...
